//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.05 at 03:10:32 PM IST 
//


package com.ekaplus.dataobject.integration.storagelocationdetail;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ekaplus.dataobject.integration.storagelocationdetail package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ekaplus.dataobject.integration.storagelocationdetail
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StorageLocationDetail }
     * 
     */
    public StorageLocationDetail createStorageLocationDetail() {
        return new StorageLocationDetail();
    }

    /**
     * Create an instance of {@link MessageInformationType }
     * 
     */
    public MessageInformationType createMessageInformationType() {
        return new MessageInformationType();
    }

    /**
     * Create an instance of {@link DocumentHeaderType }
     * 
     */
    public DocumentHeaderType createDocumentHeaderType() {
        return new DocumentHeaderType();
    }

    /**
     * Create an instance of {@link StorageLocationsType }
     * 
     */
    public StorageLocationsType createStorageLocationsType() {
        return new StorageLocationsType();
    }

    /**
     * Create an instance of {@link WarehouseRentType }
     * 
     */
    public WarehouseRentType createWarehouseRentType() {
        return new WarehouseRentType();
    }

    /**
     * Create an instance of {@link StorageLocationType }
     * 
     */
    public StorageLocationType createStorageLocationType() {
        return new StorageLocationType();
    }

}
