//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.05 at 12:06:09 PM IST 
//


package com.ekaplus.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageHeader" type="{uri:com.ekaplus.entity.StorageLocationDetail}MessageInformationType"/>
 *         &lt;element name="DocumentHeader" type="{uri:com.ekaplus.entity.StorageLocationDetail}DocumentHeaderType"/>
 *         &lt;element name="StorageLocations" type="{uri:com.ekaplus.entity.StorageLocationDetail}StorageLocationsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageHeader",
    "documentHeader",
    "storageLocations"
})
@XmlRootElement(name = "StorageLocationDetail")
public class StorageLocationDetail {

    @XmlElement(name = "MessageHeader", required = true)
    protected MessageInformationType messageHeader;
    @XmlElement(name = "DocumentHeader", required = true)
    protected DocumentHeaderType documentHeader;
    @XmlElement(name = "StorageLocations", required = true)
    protected StorageLocationsType storageLocations;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MessageInformationType }
     *     
     */
    public MessageInformationType getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageInformationType }
     *     
     */
    public void setMessageHeader(MessageInformationType value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the documentHeader property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentHeaderType }
     *     
     */
    public DocumentHeaderType getDocumentHeader() {
        return documentHeader;
    }

    /**
     * Sets the value of the documentHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentHeaderType }
     *     
     */
    public void setDocumentHeader(DocumentHeaderType value) {
        this.documentHeader = value;
    }

    /**
     * Gets the value of the storageLocations property.
     * 
     * @return
     *     possible object is
     *     {@link StorageLocationsType }
     *     
     */
    public StorageLocationsType getStorageLocations() {
        return storageLocations;
    }

    /**
     * Sets the value of the storageLocations property.
     * 
     * @param value
     *     allowed object is
     *     {@link StorageLocationsType }
     *     
     */
    public void setStorageLocations(StorageLocationsType value) {
        this.storageLocations = value;
    }

}
